# docker-compose example to be able to
# test easily this image or to give some
# config to copy/paste for an easier 
# integration in an application
version: "3.5"

services:
  shibboleth-sp:
    build: ./image/
    image: abesesr/docker-shibboleth-renater-sp:1.1.2
    ports:
      - 443:443
    environment:
      # container parameters, values comming from .env
      # (see .env-dist example)
      - RENATER_SP_TEST_OR_PROD
      - RENATER_SP_ENTITY_ID
      - RENATER_SP_ADMIN_MAIL
      - RENATER_SP_HTTPD_SERVER_NAME
      - RENATER_SP_HTTPD_LOG_LEVEL
      - RENATER_SP_HTTPD_PUBLIC_PATH_0
      - RENATER_SP_HTTPD_PUBLIC_PROXY_TO_0
      - RENATER_SP_HTTPD_PUBLIC_PATH_1
      - RENATER_SP_HTTPD_PUBLIC_PROXY_TO_1
      - RENATER_SP_HTTPD_PROTECTED_PATH_0
      - RENATER_SP_HTTPD_PROTECTED_PROXY_TO_0
      - RENATER_SP_HTTPD_PROTECTED_PATH_1
      - RENATER_SP_HTTPD_PROTECTED_PROXY_TO_1
    restart: unless-stopped
    depends_on:
      - backend-example

  # container just echoing all the HTTP headers as a JSON object
  # perfect for our shibboleth test because we need to show all the
  # attributes populated by the reverse proxy (shibboleth-sp container)
  # https://hub.docker.com/r/mendhak/http-https-echo
  backend-example-home:
    image: mendhak/http-https-echo:23
    restart: unless-stopped
  backend-example-api:
    image: mendhak/http-https-echo:23
    restart: unless-stopped
  backend-example-protected:
    image: mendhak/http-https-echo:23
    restart: unless-stopped
