# docker-compose example to be able to
# test easily this image or to give some
# config to copy/paste for an easier 
# integration in an application
version: "3.5"

services:
  shibboleth-sp:
    container_name: shibboleth-sp
    build: ./image/
    image: abesesr/docker-shibboleth-renater-sp:2.0.1
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./volume/httpd-vhosts.inc.conf
        target: /usr/local/apache2/conf/extra/httpd-vhosts-begin.inc.conf
      - type: bind
        source: ./volume/access-rotated.log
        target: /var/log/apache2/access-rotated.log
    environment:
      # ci dessous les paramètres du conteneurs avec des valeurs exemples
      ###################################################################
      # Pour basculer facilement le fournisseur de service 
      # sur la fédération RENATER de TEST ou de PROD
      RENATER_SP_TEST_OR_PROD: TEST
      # L'identifiant technique de votre fournisseur de service
      # (vous devrez forcément le modifer pour votre usage)
      RENATER_SP_ENTITY_ID: "https://v2-local.theses.fr/sp"
      # L'adresse mail de contact qui sera utilisé dans les pages
      # d'erreur d'Apache et de Shibboleth
      RENATER_SP_ADMIN_MAIL: "admin@theses.fr"
      # Les noms des fichiers des certificats utilisés par shibboleth
      # (pour la prod, vous devrez modifier ces valeurs)
      RENATER_SP_CERTIFICATE_CRT: "ssl/server-demo.crt"
      RENATER_SP_CERTIFICATE_KEY: "ssl/server-demo.key"
      # Le nom public du serveur web de votre fournisseur de service
      RENATER_SP_HTTPD_SERVER_NAME: "https://v2-local.theses.fr"
      # Le niveau et format de log du serveur apache
      # avec un exemple de format permettant de logguer les attributs venant de la fédé
      RENATER_SP_HTTPD_LOG_LEVEL: "info ssl:warn"
      RENATER_SP_HTTPD_LOG_FORMAT: '%h \"%{Shib-Identity-Provider}i\" \"%{eppn}i\" \"%{primary-affiliation}i\" \"%{supannEtablissement}i\" %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"'
      # permet de forcer apache à fermer les connexion pour pouvoir rafraîchir
      # la resolution de nom des proxypass car dans un context docker, les ip des
      # conteneurs peuvent changer
      # voir aussi https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass
      RENATER_SP_HTTPD_PROXYPASS_DISABLEREUSE: 'on'
      # Les correspondances entre les chemins dans l'URL
      # et les URL des serveurs backend proxifiés.
      # il est possible de créer 10 couples ..._PUBLIC_PATH_* / ..._PUBLIC_PROXY_TO_*
      # et 10 couples ..._PROTECTED_PATH_* / ..._PROTECTED_PROXY_TO_*
      # Il est obligatoire de positionner au moins un couple PUBLIC
      # et un couple PROTECTED
      RENATER_SP_HTTPD_PUBLIC_PATH_0: "/"
      RENATER_SP_HTTPD_PUBLIC_PROXY_TO_0: "http://backend-example-home:8080/"
      RENATER_SP_HTTPD_PUBLIC_PATH_1: "/api/"
      RENATER_SP_HTTPD_PUBLIC_PROXY_TO_1: "http://backend-example-api:8080/api/v1/"
      RENATER_SP_HTTPD_PUBLIC_PATH_2: '/([0-9]{8}[0-9X]{1})\.xml'
      RENATER_SP_HTTPD_PUBLIC_PROXY_TO_2: "http://backend-example-api:8080/api/v1/export/$1/xml"
      RENATER_SP_HTTPD_PROTECTED_PATH_0: "/my-protected-url/"
      RENATER_SP_HTTPD_PROTECTED_PROXY_TO_0: "http://backend-example-protected:8080/my-protected-url/"
      RENATER_SP_HTTPD_PROTECTED_PATH_1: "/my-protected-url2/"
      RENATER_SP_HTTPD_PROTECTED_PROXY_TO_1: "http://backend-example-protected2:8080/my-protected-url2/"
      RENATER_SP_HTTPD_PROTECTED_REQUIRE_1_0: "Require shib-attr Shib-Identity-Provider https://test-idp.federation.renater.fr/idp/shibboleth"
      RENATER_SP_HTTPD_PROTECTED_REQUIRE_1_1: "Require shib-attr eppn etudiant2@test-renater.fr"
    restart: unless-stopped
    depends_on:
      - backend-example-home

  # container just echoing all the HTTP headers as a JSON object
  # perfect for our shibboleth test because we need to show all the
  # attributes populated by the reverse proxy (shibboleth-sp container)
  # https://hub.docker.com/r/mendhak/http-https-echo
  backend-example-home:
    container_name: backend-example-home
    image: mendhak/http-https-echo:23
    restart: unless-stopped
  backend-example-api:
    container_name: backend-example-api
    image: mendhak/http-https-echo:23
    restart: unless-stopped
  backend-example-protected:
    container_name: backend-example-protected
    image: mendhak/http-https-echo:23
    restart: unless-stopped
  backend-example-protected2:
    container_name: backend-example-protected2
    image: mendhak/http-https-echo:23
    restart: unless-stopped
